// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBha41MVDAAVlvHMMbFD42hgr3UUV44R9s',
    appId: '1:199725081250:web:bd2920d371891d17d8edfb',
    messagingSenderId: '199725081250',
    projectId: 'fithub-gym-6415e',
    authDomain: 'fithub-gym-6415e.firebaseapp.com',
    storageBucket: 'fithub-gym-6415e.firebasestorage.app',
    measurementId: 'G-VM5QECR9TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIwx6r7u1x28_Vw7dFGFLoE3gziSckqgk',
    appId: '1:199725081250:android:f323c8b72927afeed8edfb',
    messagingSenderId: '199725081250',
    projectId: 'fithub-gym-6415e',
    storageBucket: 'fithub-gym-6415e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-9iWlWWQiwcFruK4UJQY4y5D3Cl2207M',
    appId: '1:199725081250:ios:b8db99ea36536f5fd8edfb',
    messagingSenderId: '199725081250',
    projectId: 'fithub-gym-6415e',
    storageBucket: 'fithub-gym-6415e.firebasestorage.app',
    iosBundleId: 'com.fithub.gym.fithubGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-9iWlWWQiwcFruK4UJQY4y5D3Cl2207M',
    appId: '1:199725081250:ios:ba56ed925186627bd8edfb',
    messagingSenderId: '199725081250',
    projectId: 'fithub-gym-6415e',
    storageBucket: 'fithub-gym-6415e.firebasestorage.app',
    iosBundleId: 'com.example.gymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBha41MVDAAVlvHMMbFD42hgr3UUV44R9s',
    appId: '1:199725081250:web:d9ad4c9f39f8bc9bd8edfb',
    messagingSenderId: '199725081250',
    projectId: 'fithub-gym-6415e',
    authDomain: 'fithub-gym-6415e.firebaseapp.com',
    storageBucket: 'fithub-gym-6415e.firebasestorage.app',
    measurementId: 'G-MZ952GWB2D',
  );
}
